### ISSUE TITLE
Starting runnable JAR throws some errors and doesn't allow Marmotta to load properly

### ISSUE THREAD

**Issue by anarchivist** [dpla-attic/marmottawrapper#3]
```
$ java -jar target/marmotta-webapp-3.2.1-0.0.1-war-exec.jar 
Oct 03, 2014 11:53:24 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Oct 03, 2014 11:53:24 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Oct 03, 2014 11:53:24 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.37
11:53:28.693 INFO  - WELD-000900: 2.1.2 (Final)
11:53:28.712 INFO  - JNDI: registering Apache Marmotta JNDI implementation ...
11:53:28.963 INFO  - JNDI: initialising Apache Marmotta Context Factory ...
11:53:28.966 INFO  - JNDI: creating Apache Marmotta Initial Context ...
11:53:29.093 INFO  - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
11:53:30.150 INFO  - Tomcat 7+ detected, CDI injection will be available in Servlets and Filters. Injection into Listeners is not supported
11:53:30.458 WARN  - WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
11:53:30.458 WARN  - WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
Oct 03, 2014 11:53:30 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.jboss.weld.environment.servlet.Listener
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type LDCacheSailProvider with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.apache.marmotta.platform.ldcache.webservices.LinkedDataCachingWebService.cacheSailProvider
  at org.apache.marmotta.platform.ldcache.webservices.LinkedDataCachingWebService.cacheSailProvider(LinkedDataCachingWebService.java:0)

    at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:368)
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:289)
    at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:135)
    at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:166)
    at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:514)
    at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
    at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
    at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
    at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

[... various INFO messages ...]

Oct 03, 2014 11:53:31 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 03, 2014 11:53:31 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 03, 2014 11:53:31 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Configuration Event Timer] but has failed to stop it. This is very likely to create a memory leak.
Oct 03, 2014 11:53:31 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Configuration Event Timer] but has failed to stop it. This is very likely to create a memory leak.
Oct 03, 2014 11:53:31 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
```

**Comment by anarchivist** [comment]
```
halfsour:marmotta-webapp mark$ curl -v http://localhost:8080/
* Adding handle: conn: 0x7fa0b900d000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fa0b900d000) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 8080 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 404 Not Found
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Content-Length: 0
< Date: Fri, 03 Oct 2014 15:57:49 GMT
< 
* Connection #0 to host localhost left intact
halfsour:marmotta-webapp mark$ curl -v http://localhost:8080/marmotta
* Adding handle: conn: 0x7fbb62004000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fbb62004000) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 8080 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /marmotta HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 404 Not Found
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Content-Length: 0
< Date: Fri, 03 Oct 2014 15:57:51 GMT
< 
* Connection #0 to host localhost left intact
```
